### ISSUE TITLE
신호 최적화 실행시 오류 발생

### ISSUE THREAD

**Issue by kusubang** [etri-city-traffic-brain/visualization-tool#95]
신호 최적화 실행시 다음과 같은 오류 발생

```
run --rm --name S-166593626023-0
-v /home/ubuntu/uniq-simv2/data:/uniq/data
-v /home/ubuntu/uniq-simv2/opt/OPTI_202309_00057/input:/uniq/optimizer/input
-v /home/ubuntu/uniq-simv2/opt/OPTI_202309_00057/output:/uniq/optimizer/output
-v /home/ubuntu/uniq-simv2/opt/OPTI_202309_00057/model:/uniq/optimizer/model
-v /home/ubuntu/uniq-simv2/opt:/uniq/optimizer/opt
images4uniq/optimizer:v3.0.20230814
python ./run_modutech.py
--mode test
--map doan
--start-time 25200
--end-time 28740
--target-TL "SA 28"
--reward-func wq
--method sappo
--action ga
--epoch 5
--model-save-period 1
--model-num 0
--state vd
--mem-len 16



--------------error log----------------------
2023-09-27 14:10:55.393515: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-09-27 14:10:55.393560: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-09-27 14:10:56.756758: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-09-27 14:10:56.756798: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-09-27 14:10:56.756844: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a53f96f1adb6): /proc/driver/nvidia/version does not exist
scenarioFile: /uniq/optimizer/./input/doan_test.scenario.json
Loading Road Network ... done
Loading Vehicle Demand ... done
Loading Traffic Signal System ... done
[Simulation Output (Periodic)] >> output/test/S-166593626023-0_PeriodicOutput.csv
[Progress status] >> output/test/progress.txt
--- Configuration Done ---
[Simulation Info]
Input
        -Simulation Name: S-166593626023-0
        -Road Network: /uniq/optimizer/./input/../../data/scenario/doan/doan.node.xml, /uniq/optimizer/./input/../../data/scenario/doan/doan.edge.xml, /uniq/optimizer/./input/../../data/scenario/doan/doan.connection.xml
        -Vehicle Demand: /uniq/optimizer/./input/../../data/route/doan/doan_20220601.rou.xml
        -Traffic Light System: /uniq/optimizer/./input/../../data/scenario/doan/doan.tss.xml
        -Time Range: 25200~28740
Output
        -Output Per Period: output/test/S-166593626023-0_PeriodicOutput.csv

[Simulation Start]
[Jump currentStep from 0 to 0]
[Simulation End]
Elapsed Time: 0 seconds
handleConnection() Connected to VisServer: 101.79.1.124:1337
[InitMsg] timestamp=1695791459, simulationId=[S-166593626023-0]
handleRead() Received MsgHeader, received=16
handleRead() Received SET message, type=10, bodySize=17, received_bytes=17
[SetMsg] timestamp=4789768766086524928, bodySize=17, roadType=cell, extend=127.337303,36.348370 127.343033,36.342529
[StatusMsg] timestamp=1695791459, status=1, progress=4294966585
socket closed 101.79.1.124
2023-09-27 14:11:02.804531: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
launched at 2023-09-27 14:10:57.959773
Mode: test
/usr/local/lib/python3.6/dist-packages/gym/core.py:27: UserWarning: WARN: Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+
  "Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+"
/usr/local/lib/python3.6/dist-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/usr/local/lib/python3.6/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")
Traceback (most recent call last):
  File "./run_modutech.py", line 513, in <module>
    testSappo(args)
  File "./run_modutech.py", line 278, in testSappo
    reward, imp_rate = _testSappo(config, env_name=env_name, agent_name=agent_name)
  File "./run_modutech.py", line 304, in _testSappo
    if args.action != 'fx': agent.load_agent(trial=args.model_num)
  File "/uniq/optimizer/rl_agent.py", line 71, in load_agent
    agent.loadModel(fn_prefix)
  File "/uniq/optimizer/policy/dirichlet_ppoTF2.py", line 1245, in loadModel
    self.actor.model.load_weights(f"{fn_prefix}_{self.id}_actor.h5")
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 2361, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.6/dist-packages/keras/saving/hdf5_format.py", line 713, in load_weights_from_hdf5_group
    backend.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend.py", line 3775, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype_numpy(x)))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 902, in assign
    (tensor_name, self._shape, value_tensor.shape))
ValueError: Cannot assign to variable dense/kernel:0 due to variable shape (282, 1024) and value shape (321, 1024) are incompatible
<---- optimiztion training error start ----->
Error: stdout scenarioFile: /uniq/optimizer/./input/doan_test.scenario.json
Loading Road Network ... done
Loading Vehicle Demand ... done
Loading Traffic Signal System ... done
[Simulation Output (Periodic)] >> output/test/S-166593626023-0_PeriodicOutput.csv
[Progress status] >> output/test/progress.txt
--- Configuration Done ---
[Simulation Info]
Input
        -Simulation Name: S-166593626023-0
        -Road Network: /uniq/optimizer/./input/../../data/scenario/doan/doan.node.xml, /uniq/optimizer/./input/../../data/scenario/doan/doan.edge.xml, /uniq/optimizer/./input/../../data/scenario/doan/doan.connection.xml
        -Vehicle Demand: /uniq/optimizer/./input/../../data/route/doan/doan_20220601.rou.xml
        -Traffic Light System: /uniq/optimizer/./input/../../data/scenario/doan/doan.tss.xml
        -Time Range: 25200~28740
Output
        -Output Per Period: output/test/S-166593626023-0_PeriodicOutput.csv

[Simulation Start]
[Jump currentStep from 0 to 0]
[Simulation End]
Elapsed Time: 0 seconds
handleConnection() Connected to VisServer: 101.79.1.124:1337
[InitMsg] timestamp=1695791459, simulationId=[S-166593626023-0]
handleRead() Received MsgHeader, received=16
handleRead() Received SET message, type=10, bodySize=17, received_bytes=17
[SetMsg] timestamp=4789768766086524928, bodySize=17, roadType=cell, extend=127.337303,36.348370 127.343033,36.342529
[StatusMsg] timestamp=1695791459, status=1, progress=4294966585
launched at 2023-09-27 14:10:57.959773
Mode: test
, stderr 2023-09-27 14:10:55.393515: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-09-27 14:10:55.393560: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-09-27 14:10:56.756758: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-09-27 14:10:56.756798: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-09-27 14:10:56.756844: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a53f96f1adb6): /proc/driver/nvidia/version does not exist
2023-09-27 14:11:02.804531: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.6/dist-packages/gym/core.py:27: UserWarning: WARN: Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+
  "Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+"
/usr/local/lib/python3.6/dist-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/usr/local/lib/python3.6/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")
Traceback (most recent call last):
  File "./run_modutech.py", line 513, in <module>
    testSappo(args)
  File "./run_modutech.py", line 278, in testSappo
    reward, imp_rate = _testSappo(config, env_name=env_name, agent_name=agent_name)
  File "./run_modutech.py", line 304, in _testSappo
    if args.action != 'fx': agent.load_agent(trial=args.model_num)
  File "/uniq/optimizer/rl_agent.py", line 71, in load_agent
    agent.loadModel(fn_prefix)
  File "/uniq/optimizer/policy/dirichlet_ppoTF2.py", line 1245, in loadModel
    self.actor.model.load_weights(f"{fn_prefix}_{self.id}_actor.h5")
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 2361, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.6/dist-packages/keras/saving/hdf5_format.py", line 713, in load_weights_from_hdf5_group
    backend.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend.py", line 3775, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype_numpy(x)))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 902, in assign
    (tensor_name, self._shape, value_tensor.shape))
ValueError: Cannot assign to variable dense/kernel:0 due to variable shape (282, 1024) and value shape (321, 1024) are incompatible

<---- optimiztion training error end ----->
```

**Comment by kusubang** [comment]
신호최적화 컨테이너 실행시 --map 옵션에 사용한 지도가 없어서 발생하는 문제였음

- 존재하는 지도를 사용하도록 조치하여 해결
